// <auto-generated />
using EuroJudoWebContestSheets.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EuroJudoWebContestSheets.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20181229141810_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("EuroJudoWebContestSheets.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.Property<int>("SheetSize");

                    b.Property<int>("TournamentID");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EuroJudoWebContestSheets.Models.ContestSheetData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryID");

                    b.Property<string>("CompeditorBlue");

                    b.Property<string>("CompeditorWhite");

                    b.Property<int>("Contest");

                    b.Property<int>("IponBlue");

                    b.Property<int>("IponWhite");

                    b.Property<int>("ShidoBlue");

                    b.Property<int>("ShidoWhite");

                    b.Property<bool>("ShowSimpleScore");

                    b.Property<int>("TournamentID");

                    b.Property<int>("WazaariBlue");

                    b.Property<int>("WazaariWhite");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("ContestSheetData");
                });

            modelBuilder.Entity("EuroJudoWebContestSheets.Models.Tournament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TournamentName");

                    b.HasKey("ID");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("EuroJudoWebContestSheets.Models.ContestSheetData", b =>
                {
                    b.HasOne("EuroJudoWebContestSheets.Models.Category")
                        .WithMany("SheetData")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
